apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  secret.txt: Y2VydGlmaWNhdGU=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  config.txt: "helo"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: gcr.io/qwiklabs-gcp-04-13d0a6e21aa2/my-ser:1.0.0
        env:
        - name: MY_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: config.txt
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: secret.txt
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
